version: '3'

services:
  mongo:
    image: mongo:3.4
    ports:
      - '27017'
    volumes:
      - /data/mongo/db:/home/phillip/data/db
    restart: always
    command: mongod --quiet

  neo4j:
    image: neo4j:3.3
    environment:
      - NEO4J_AUTH=none
    volumes:
      - /data/neo4j:/home/phillip/data
    restart: always
    ports:
      - '7474'
      - '7687'

  app:
    build: .
    ports:
      - '9000:9000'
    environment:
      - NODE_ENV=production
    restart: always
    depends_on:
      - mongo
      - neo4j
    links:
      - mongo
      - neo4j
