version: '3'

services:
  mongo:
    image: mongo:3.4
    ports:
      - '27017'
    command: mongod --quiet

  neo4j:
    image: neo4j:3.2
    environment:
      - NEO4J_AUTH=none
    ports:
      - '7474'
      - '7687'

  app:
    build: .
    ports:
      - '9002:9002'
    environment:
        - NODE_ENV=production
    depends_on:
      - mongo
      - neo4j
    links:
      - mongo
      - neo4j
